---
- name: Ruby | Install RVM
  shell: curl -L https://get.rvm.io | bash -s stable --quiet-curl --auto-dotfiles --ruby=2.1.3 creates=/home/{{ user }}/.rvm
  tags: ruby
  ignore_errors: true
  when: ruby_install is defined
        and ruby_install == "y"

- name: Ruby | Update RubyGems via RVM
  shell: PATH=$PATH:/home/{{ user }}/.rvm/bin rvm rubygems latest
  tags: ruby
  when: ruby_install is defined
        and ruby_install == "y"
